### ISSUE TITLE
No output and warning when dealing with UTF-8 characters

### ISSUE THREAD

**Issue by alexlawrence** [n0ts/ansible-human_log#1]
When trying to execute a playbook which outputs UTF-8 characters the following warning will be displayed:

> [WARNING]: Error when using >: 'ascii' codec can't encode character u'\u03bc'
> in position 696: ordinal not in range(128)

Also no output will be generated.

I managed to change the encoding so that it will work but it seems rather like a hack than a correct solution. 

Any ideas?

**Comment by ssbarnea** [comment]
Some problem here
```
 [WARNING]: Failure when attempting to use callback plugin (</media/psf/Home/devops/callback_plugins/human_log.CallbackModule object at 0x7f279db4e110>): 'ascii' codec can't encode character
u'\u2018' in position 18: ordinal not in range(128)
```

**Comment by ssbarnea** [comment]
@alexlawrence can you make you change public so I can debug it?

**Comment by alexlawrence** [comment]
I replaced line 49-51 of https://github.com/n0ts/ansible-human_log/blob/b8c5f5dfcbbf8bcf8bfffc52738c4cf3fd685ca9/human_log.py with

```python
# The following two lines are a hack to make it work with UTF-8 characters
if type(output) != list:
  output = output.encode('utf-8', 'replace')
```

Honestly, I have not really an idea what this code is doing. This is the outcome of a few minutes googling and a bit of trial and error. I don´t know about Python string encoding.

**Comment by ssbarnea** [comment]
Can we have the PR merged? It is not cool to have bugs with PRs open for such a long time.

**Comment by n0ts** [comment]
#9  is merged, Thanks.
