### ISSUE TITLE
Human readable output doesn't apply to log file

### ISSUE THREAD

**Issue by Harosgr** [n0ts/ansible-human_log#2]
The human readable output doesn't apply to the text written in the ansible logfile (if enabled).

**Comment by jinesh-choksi** [comment]
See: https://github.com/jinesh-choksi/ansible-human_log

I amended the code to send human friendly output to the log file and leave Ansible's default output as it normally is. If you want to see the same human friendly output onscreen as well as in the log file, then read the changelog.md file in the above link on what you need to amend to have that functionality.

**Comment by ssbarnea** [comment]
I don't like the idea of changing the current behaviour. How about adding some configuration options inside ansible.cfg file?

**Comment by Harosgr** [comment]
@jinesh-choksi thanks for the fork! I will give a look. =)
@ssbarnea configuration options inside ansible.cfg seems more difficult to be done. You need to contribute to the main ansible project to provide such a function.

What it would be really nice, is a plugin which by editing / commenting a line, will let you choose between human readable stdout only, human readable logs only, or both. More or less like what @jinesh-choksi did...
