### ISSUE TITLE
Double output with ignore_errors: yes

### ISSUE THREAD

**Issue by Harosgr** [n0ts/ansible-human_log#3]
If you run a command in ansible with "ignore_errors: yes", in case of an error, the non-formated ouput is printed, and then the formated ouput follows...

I am copy pasting part of my output in order for you to better understand the second problem.

> /tdpvmware/fcm/fmcima -l /home/tdpvmware/tdpvmware/config -N DEVICE_CLASS:FCBACKUP_SLM.0 -f backup' returned with code 0.", "#CHILD lunid:6005076801828070F800000000000211", "#PARENT lunname:V-slmesx01_lun0002", "#WARNING FMM1554W The agent 'acsgen V. 4.1.4.0' terminated with exit code 1.", "#INFO FMM0020I End of program at: Fri Mar 11 16:23:03 2016.", "#INFO FMM0021I Elapsed time: 01 min 38 sec.", "#INFO FMM0024I Return code is: 1.", "#PARAM STATUS=warning", "#END RUN 636 20160311162303884", "#END TASK 114", "#INFO FMM16014I The return code is 1.", "#END"], "warnings": []}
> ...ignoring
> **_[after that part the ouput is displayed again but now formated]_**
> cmd: /opt/tivoli/tsm/tdpvmware/common/scripts/vmcli -f backup -T 114 --runnow
> start: 2016-03-11 16:21:24.221963
> end: 2016-03-11 16:23:05.543694
> delta: 0:01:41.321731
> stdout: #TASK 114 backup 20131008162736229

**Comment by n0ts** [comment]
Hello, It is normal situation.
