### ISSUE TITLE
Is this repository abandoned?

### ISSUE THREAD

**Issue by ssbarnea** [n0ts/ansible-human_log#6]
I am wondering if there are any plans on getting some basic maintenance on this repository as it seems that it listed at least one PR which was ignored for few good months.

If there is no interest in keeping this code maintained we could know and fork it, letting others know that is it maintained in a different place. Thanks.

**Comment by alexlawrence** [comment]
Sorry for beating the dead but should `stdout_callback = debug` do the same as this plugin did? For me changing the setting (via config or env var) does not do anything. I'm asking his here because I have a hard time finding good docs on this topic.

Help is much appreciated :)

**Comment by n0ts** [comment]
Sorry, I update latest version.
Thanks!

**Comment by ssbarnea** [comment]
I think that it should be documented that this plugin is no longer needed on newer versions of ansible as it was included in the code with the "debug" name. Please update the README to state that.

**Comment by n0ts** [comment]
@ssbarnea What is "debug" name mean?

**Comment by ssbarnea** [comment]
You can enable it using `ANSIBLE_STDOUT_CALLBACK=debug` or inside `ansible.cfg` via `stdout_callback = debug`. Source code at https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/callback/debug.py

Please update both README and the description text of the repo stating this, it will save people many hours. 

Also, if you want to improve it, feel free to raise pull requests to Ansible. You will be surprised how easy is to contribute directly to Ansible. The team has a 3mo long new release cadence, which means that new features will be available in less than 3 months. Also they backport bug-fixes for two previous versions.
